




species = specGen();
nation = nationGen();
gender = genderGen();
rank = rankGen();
name = nameGen();
surname = surNameGen();
age = ageGen();
pos = posGen();
pers = persGen();
skin = skinGen();
hair = hairGen();
eye = eyeGen();
body = bodyGen();
hobby = hobGen();
notes = notesGen();
appearance = appearanceGen(body, skin, eye, hair);
var scienceOfficer = new Character(name, surname, gender, age,species, pers, hobby);
characterArray.push(scienceOfficer);
$("#science-officer .name").text(name + surname);
$("#science-officer .species").text(species);
$("#science-officer .gender").text(gender);
$("#science-officer .age").text(age);
$("#science-officer .position").text(pos);
$("#science-officer .personality").text(pers);
$("#science-officer .appearance").text(appearance);
$("#science-officer .hobby").text(hobby);
$("#science-officer .notes").text(notes);

species = specGen();
nation = nationGen();
gender = genderGen();
rank = rankGen();
name = nameGen();
surname = surNameGen();
age = ageGen();
pos = posGen();
pers = persGen();
skin = skinGen();
hair = hairGen();
eye = eyeGen();
body = bodyGen();
hobby = hobGen();
notes = notesGen();
appearance = appearanceGen(body, skin, eye, hair);
var securityOfficer = new Character(name, surname, gender, age,species, pers, hobby);
characterArray.push(securityOfficer);
$("#security-officer .name").text(name + surname);
$("#security-officer .species").text(species);
$("#security-officer .gender").text(gender);
$("#security-officer .age").text(age);
$("#security-officer .position").text(pos);
$("#security-officer .personality").text(pers);
$("#security-officer .appearance").text(appearance);
$("#security-officer .hobby").text(hobby);
$("#security-officer .notes").text(notes);

species = specGen();
nation = nationGen();
gender = genderGen();
rank = rankGen();
name = nameGen();
surname = surNameGen();
age = ageGen();
pos = posGen();
pers = persGen();
skin = skinGen();
hair = hairGen();
eye = eyeGen();
body = bodyGen();
hobby = hobGen();
notes = notesGen();
appearance = appearanceGen(body, skin, eye, hair);
var doctor = new Character(name, surname, gender, age,species, pers, hobby);
characterArray.push(doctor);
$("#doctor .name").text(name + surname);
$("#doctor .species").text(species);
$("#doctor .gender").text(gender);
$("#doctor .age").text(age);
$("#doctor .position").text(pos);
$("#doctor .personality").text(pers);
$("#doctor .appearance").text(appearance);
$("#doctor .hobby").text(hobby);
$("#doctor .notes").text(notes);

species = specGen();
nation = nationGen();
gender = genderGen();
rank = rankGen();
name = nameGen();
surname = surNameGen();
age = ageGen();
pos = posGen();
pers = persGen();
skin = skinGen();
hair = hairGen();
eye = eyeGen();
body = bodyGen();
hobby = hobGen();
notes = notesGen();
appearance = appearanceGen(body, skin, eye, hair);
var engineer = new Character(name, surname, gender, age,species, pers, hobby);
characterArray.push(engineer);
$("#engineer .name").text(name + surname);
$("#engineer .species").text(species);
$("#engineer .gender").text(gender);
$("#engineer .age").text(age);
$("#engineer .position").text(pos);
$("#engineer .personality").text(pers);
$("#engineer .appearance").text(appearance);
$("#engineer .hobby").text(hobby);
$("#engineer .notes").text(notes);

species = specGen();
nation = nationGen();
gender = genderGen();
rank = rankGen();
name = nameGen();
surname = surNameGen();
age = ageGen();
pos = posGen();
pers = persGen();
skin = skinGen();
hair = hairGen();
eye = eyeGen();
body = bodyGen();
hobby = hobGen();
notes = notesGen();
appearance = appearanceGen(body, skin, eye, hair);
var counselor = new Character(name, surname, gender, age,species, pers, hobby);
characterArray.push(counselor);
$("#counselor .name").text(name + surname);
$("#counselor .species").text(species);
$("#counselor .gender").text(gender);
$("#counselor .age").text(age);
$("#counselor .position").text(pos);
$("#counselor .personality").text(pers);
$("#counselor .appearance").text(appearance);
$("#counselor .hobby").text(hobby);
$("#counselor .notes").text(notes);
